sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.3" ]]; then pip install --upgrade pip setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then pip install --upgrade "pip<10.0" "setuptools<24.0"; fi
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
  - pip install .
script:
  - cleanup .
  - coverage run --source=admin_scripts setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: swv8o7E8RGK9w1L76l1uKUQGJfH87FvT+Ts34OZ/zgrrdrXQnhzPusTw5sys8osiEeBZwMhFZ2w3BAGT4YeU2cIgLBEh99MRRCBreZ2vNWjKw+bMrFRV4l32Omfx5l1bTJmds4ATSfed4N8aHtlrx6FCbuedTibvhwH+8SM/1R8=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
