sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install admin_scripts
  - pip install coveralls
  - pip install twine
script:
  - cleanup .
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=admin_scripts setup.py test; else python setup.py test; fi
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: QWFG1yE3AEumxZLCMkz0ryYk71tSbI3Twa55dypivBUrGYilR4Sbl9GL5W6KHI30CiO7GBNqiKcvlTV/arnnDinB2j8avoyjcARwVYtzJb9OZyTmI82eSS3y46n+yDMf58wE8oMEKVQs6KdFcGxtatNeHWWwy/GmgQAjg6Oy5ww=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
