dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install "cryptography<2.9"; fi
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .
script:
  - cleanup .
  - coverage run --source=admin_scripts setup.py test
after_success: coveralls
