name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [
          2.7,
          3.5,
          3.6,
          3.7,
          3.8,
          3.9,
          "3.10",
          "3.11",
          "3.12",
          latest,
          rc
        ]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - run: pip install -r requirements.txt
      - run: pip install --no-cache-dir .
      - run: cleanup .
      - run: |
          pip install pytest
          HTTPBIN=httpbin.bemisc.com pytest
      - run: python setup.py test
        if: matrix.python-version != '3.12' && matrix.python-version != 'latest'
  build-pypy:
    name: Build PyPy
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [2.7, 3.6]
    runs-on: ubuntu-latest
    container: pypy:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - run: pypy --version
      - run: pip install -r requirements.txt
      - run: pip install --no-cache-dir .
      - run: cleanup .
      - run: |
          pip install pytest
          HTTPBIN=httpbin.bemisc.com pytest
      - run: pypy setup.py test
        if: matrix.python-version != '3.12' && matrix.python-version != 'latest'
